/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SI_Lab2_141530;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void test1() {
        assertEquals(SILab2.checkPrime(2), true);
        assertEquals(SILab2.checkPrime(6), false);
    }
}
